/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/computers_1-transformed.glb')
  const instances = useMemo(
    () => ({
      Object: nodes.Object_4,
      Object1: nodes.Object_16,
      Object3: nodes.Object_52,
      Object13: nodes.Object_172,
      Object14: nodes.Object_174,
      Object23: nodes.Object_22,
      Object24: nodes.Object_26,
      Object32: nodes.Object_178,
      Object36: nodes.Object_28,
      Object44: nodes.Object_206,
      Object45: nodes.Object_207,
      Object46: nodes.Object_215,
      Object47: nodes.Object_216,
      Sphere: nodes.Sphere,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  const { nodes, materials } = useGLTF('/computers_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.731, 0.629, -0.522]} rotation={[0, 1.087, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_212.geometry}
          material={materials.Texture}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_213.geometry}
          material={materials.Screen}
        />
      </group>
      <group position={[-1.43, 2.496, -1.8]} rotation={[0, 1.002, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_209.geometry}
          material={materials.Texture}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_210.geometry}
          material={materials.Screen}
        />
      </group>
      <group position={[-3.417, 3.056, 1.303]} rotation={[0, 1.222, 0]} scale={0.9}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_221.geometry}
          material={materials.Texture}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_222.geometry}
          material={materials.Screen}
        />
      </group>
      <group position={[0.27, 1.529, -2.613]}>
        <instances.Object44 />
        <instances.Object45 />
      </group>
      <group position={[3.11, 2.145, -0.18]} rotation={[0, -0.793, 0]} scale={0.81}>
        <instances.Object44 />
        <instances.Object45 />
      </group>
      <group position={[1.845, 0.377, -1.771]} rotation={[0, -Math.PI / 9, 0]}>
        <instances.Object46 />
        <instances.Object47 />
      </group>
      <group position={[-3.899, 4.287, -2.642]} rotation={[0, 0.539, 0]}>
        <instances.Object46 />
        <instances.Object47 />
      </group>
      <group position={[0.955, 4.282, -4.203]} rotation={[0.003, -0.647, 0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_227.geometry}
          material={materials.Texture}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_228.geometry}
          material={materials.Screen}
        />
      </group>
      <group position={[4.683, 4.29, -1.558]} rotation={[0, -Math.PI / 3, 0]}>
        <instances.Object46 />
        <instances.Object47 />
      </group>
      <instances.Object
        position={[0.165, 0.794, -1.972]}
        rotation={[-0.544, 0.929, -1.119]}
        scale={0.5}
      />
      <instances.Object
        position={[-2.793, 0.27, 1.816]}
        rotation={[-1.44, 1.219, 1.432]}
        scale={0.5}
      />
      <instances.Object
        position={[-5.603, 4.615, -0.027]}
        rotation={[-1.955, 0.163, 1.202]}
        scale={0.5}
      />
      <instances.Object
        position={[2.621, 1.985, -2.473]}
        rotation={[-0.419, -0.704, -1.851]}
        scale={0.5}
      />
      <instances.Object
        position={[4.598, 3.459, 1.19]}
        rotation={[-1.236, -0.719, 0.48]}
        scale={0.5}
      />
      <instances.Object1 position={[0.63, 0, -3]} rotation={[0, 0.17, 0]} scale={1.52} />
      <instances.Object1
        position={[-2.36, 0.32, -2.018]}
        rotation={[0, 0.534, -Math.PI / 2]}
        scale={1.52}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.Texture}
        position={[-2.424, 0.938, -2.247]}
        rotation={[0, 0.136, Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object1
        position={[-3.528, 0, 0.586]}
        rotation={[Math.PI, -1.085, Math.PI]}
        scale={1.52}
      />
      <instances.Object1 position={[-3.528, 1.528, 0.586]} rotation={[0, 0.911, 0]} scale={1.52} />
      <instances.Object1
        position={[3.423, 0, 0.005]}
        rotation={[-Math.PI, 1.127, -Math.PI]}
        scale={1.52}
      />
      <instances.Object1
        position={[4.086, 2.183, 2.41]}
        rotation={[0, -1.548, 1.571]}
        scale={1.52}
      />
      <instances.Object3
        position={[4.314, 1.565, 2.343]}
        rotation={[0, -1.149, -Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object3
        position={[-3.79, 0, 1.656]}
        rotation={[Math.PI, -1.393, 0]}
        scale={-1.52}
      />
      <instances.Object3
        position={[-3.79, 1.528, 1.656]}
        rotation={[0, 1.218, -Math.PI]}
        scale={-1.52}
      />
      <instances.Object1 position={[-3.693, 0, 2.585]} rotation={[0, -1.568, 0]} scale={1.52} />
      <instances.Object1
        position={[-5.36, 2.183, 0.811]}
        rotation={[0, 0.772, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object3
        position={[-5.564, 1.565, 0.69]}
        rotation={[0, 1.171, -Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object1
        position={[-5.474, 2.794, 0.745]}
        rotation={[Math.PI, -1.155, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object3
        position={[-5.289, 3.412, 0.894]}
        rotation={[Math.PI, -0.757, -Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object1 position={[-5.283, 0, -2.328]} rotation={[0, 0.755, 0]} scale={1.52} />
      <instances.Object1
        position={[-5.486, 0, -1.385]}
        rotation={[Math.PI, -0.985, Math.PI]}
        scale={1.52}
      />
      <instances.Object1 position={[-3.012, 0, -3.79]} rotation={[0, 0.597, 0]} scale={1.52} />
      <instances.Object1
        position={[-2.082, 0, -4.324]}
        rotation={[Math.PI, -0.597, Math.PI]}
        scale={1.52}
      />
      <instances.Object1 position={[-1.016, 0, -4.489]} rotation={[0, 0.308, 0]} scale={1.52} />
      <instances.Object1
        position={[-5.315, 1.833, -1.412]}
        rotation={[0, 1.062, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object1
        position={[-4.181, 1.833, -3.064]}
        rotation={[-Math.PI, -0.465, -Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object1
        position={[-1.758, 1.833, -3.605]}
        rotation={[0, -1.165, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object1
        position={[-0.254, 1.833, -5.542]}
        rotation={[0, 1.553, 1.571]}
        scale={1.52}
      />
      <instances.Object1
        position={[-5.283, 2.143, -2.328]}
        rotation={[Math.PI, -0.755, Math.PI]}
        scale={1.52}
      />
      <instances.Object1 position={[-5.486, 2.143, -1.385]} rotation={[0, 0.985, 0]} scale={1.52} />
      <instances.Object1
        position={[-3.012, 2.143, -3.79]}
        rotation={[Math.PI, -0.597, Math.PI]}
        scale={1.52}
      />
      <instances.Object1 position={[-2.082, 2.143, -4.324]} rotation={[0, 0.597, 0]} scale={1.52} />
      <instances.Object1
        position={[-1.016, 2.143, -4.489]}
        rotation={[Math.PI, -0.308, Math.PI]}
        scale={1.52}
      />
      <instances.Object1
        position={[-5.315, 3.976, -1.412]}
        rotation={[0, 1.062, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object1
        position={[-4.181, 3.976, -3.064]}
        rotation={[-Math.PI, -0.465, -Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object1
        position={[-1.173, 3.976, -4.449]}
        rotation={[0, 0.168, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object1
        position={[-0.941, 3.976, -4.664]}
        rotation={[Math.PI, 0.018, -Math.PI / 2]}
        scale={1.52}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials.Texture}
        position={[5.531, 2.183, 0.174]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials.Texture}
        position={[5.736, 1.565, 0.053]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials.Texture}
        position={[5.646, 2.794, 0.107]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials.Texture}
        position={[5.461, 3.412, 0.256]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        material={materials.Texture}
        position={[4.856, 0, -2.541]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials.Texture}
        position={[5.059, 0, -1.597]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials.Texture}
        position={[2.585, 0, -4.002]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials.Texture}
        position={[1.655, 0, -4.536]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials.Texture}
        position={[0.59, 0, -4.701]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <instances.Object13
        position={[4.888, 1.833, -1.624]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <instances.Object14
        position={[3.754, 1.833, -3.277]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials.Texture}
        position={[1.332, 1.833, -3.817]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_180.geometry}
        material={materials.Texture}
        position={[4.856, 2.143, -2.541]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials.Texture}
        position={[5.059, 2.143, -1.597]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_188.geometry}
        material={materials.Texture}
        position={[2.585, 2.143, -4.002]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_192.geometry}
        material={materials.Texture}
        position={[1.655, 2.143, -4.536]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_194.geometry}
        material={materials.Texture}
        position={[0.59, 2.143, -4.701]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <instances.Object13
        position={[4.888, 3.976, -1.624]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <instances.Object14
        position={[3.754, 3.976, -3.277]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_200.geometry}
        material={materials.Texture}
        position={[0.746, 3.976, -4.662]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.Texture}
        position={[-0.186, 0, -2.962]}
        rotation={[0, -0.064, 0]}
        scale={1.52}
      />
      <instances.Object23
        position={[-2.288, 1.56, -2.263]}
        rotation={[0, -0.012, -Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object24
        position={[-2.195, 2.188, -1.867]}
        rotation={[0, 0.512, Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object23
        position={[-2.896, 0.3, -1.466]}
        rotation={[Math.PI, -1.347, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object23 position={[3.224, 0, -0.804]} rotation={[0, -1.324, 0]} scale={1.52} />
      <instances.Object23
        position={[3.53, 1.834, 0.44]}
        rotation={[-Math.PI, 1.324, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object23
        position={[4.255, 0.943, 2.219]}
        rotation={[0, -1.002, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object24
        position={[3.87, 0.315, 2.35]}
        rotation={[0, -1.526, -1.571]}
        scale={-1.52}
      />
      <instances.Object23
        position={[-5.614, 0.943, 0.817]}
        rotation={[0, 1.318, 1.571]}
        scale={1.52}
      />
      <instances.Object24
        position={[-5.257, 0.315, 1.01]}
        rotation={[0, 0.795, -Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object23
        position={[-5.39, 4.034, 0.986]}
        rotation={[Math.PI, -0.609, Math.PI / 2]}
        scale={1.52}
      />
      <instances.Object24
        position={[-5.696, 4.662, 0.718]}
        rotation={[Math.PI, -1.133, -Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object23 position={[-5.952, 0, -0.641]} rotation={[0, 0.953, 0]} scale={1.52} />
      <instances.Object23
        position={[-4.476, 0, -2.749]}
        rotation={[Math.PI, -0.568, Math.PI]}
        scale={1.52}
      />
      <instances.Object23 position={[-3.716, 0, -2.886]} rotation={[0, 0.644, 0]} scale={1.52} />
      <instances.Object23
        position={[-0.084, 0, -5.026]}
        rotation={[Math.PI, -0.039, Math.PI]}
        scale={1.52}
      />
      <instances.Object24
        position={[-4.194, 1.836, -2.768]}
        rotation={[Math.PI, -0.655, -Math.PI / 2]}
        scale={-1.52}
      />
      <instances.Object23
        position={[-5.952, 2.143, -0.641]}
        rotation={[Math.PI, -0.953, Math.PI]}
        scale={1.52}
      />
      <instances.Object23
        position={[-4.476, 2.143, -2.749]}
        rotation={[0, 0.568, 0]}
        scale={1.52}
      />
      <instances.Object23
        position={[-3.727, 2.143, -3.1]}
        rotation={[Math.PI, -0.644, Math.PI]}
        scale={1.52}
      />
      <instances.Object23
        position={[-0.084, 2.143, -5.026]}
        rotation={[0, 0.039, 0]}
        scale={1.52}
      />
      <instances.Object24
        position={[-4.194, 3.979, -2.768]}
        rotation={[Math.PI, -0.655, -Math.PI / 2]}
        scale={-1.52}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials.Texture}
        position={[5.786, 0.943, 0.18]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials.Texture}
        position={[5.428, 0.315, 0.373]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials.Texture}
        position={[5.562, 4.034, 0.348]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials.Texture}
        position={[5.868, 4.662, 0.081]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials.Texture}
        position={[5.525, 0, -0.854]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials.Texture}
        position={[4.05, 0, -2.962]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials.Texture}
        position={[3.289, 0, -3.098]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <instances.Object32 position={[3.767, 1.836, -2.98]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_182.geometry}
        material={materials.Texture}
        position={[5.525, 2.143, -0.854]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_186.geometry}
        material={materials.Texture}
        position={[4.05, 2.143, -2.962]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_190.geometry}
        material={materials.Texture}
        position={[3.3, 2.143, -3.312]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <instances.Object32 position={[3.767, 3.979, -2.98]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <instances.Object36 position={[0.353, 2.352, -3.336]} rotation={[-0.255, 0, 0]} />
      <instances.Object36 position={[0.183, 2.801, -2.854]} rotation={[0.093, 0.146, -0.014]} />
      <instances.Object36
        position={[1.895, 0, -1.944]}
        rotation={[0, -0.436, 0]}
        scale={[1.5, 1, 1.5]}
      />
      <instances.Object36 position={[1.862, 1.61, -1.807]} rotation={[0, -Math.PI / 3, 0]} />
      <instances.Object36 position={[3.954, 2.491, 1.607]} rotation={[0, -Math.PI / 3, 0]} />
      <instances.Object36 position={[-1.095, 4.291, -4.434]} rotation={[0, 0.357, 0]} />
      <instances.Object36 position={[-5.246, 4.291, -1.466]} rotation={[0, 1.246, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_204.geometry}
        material={materials.Texture}
        position={[3.198, 4.291, -3.092]}
        rotation={[-Math.PI, 0.563, 0]}
        scale={-1}
      />
      <instances.Sphere position={[-0.408, 1.095, -2.212]} scale={0.009} />
      <instances.Sphere position={[0.588, 1.323, -2.222]} scale={0.009} />
      <instances.Sphere position={[1.772, 1.909, -1.165]} scale={0.009} />
      <instances.Sphere position={[2.438, 1.096, -0.786]} scale={0.009} />
      <instances.Sphere position={[4.868, 3.799, -0.097]} scale={0.009} />
      <instances.Sphere position={[1.93, 3.795, -3.69]} scale={0.009} />
      <instances.Sphere position={[-2.346, 3.799, -3.479]} scale={0.009} />
      <instances.Sphere position={[-4.706, 4.589, -1.812]} scale={0.009} />
      <instances.Sphere position={[-3.032, 2.853, 1.195]} scale={0.009} />
      <instances.Sphere position={[-1.206, 1.731, -1.489]} scale={0.009} />
    </group>
  )
}

useGLTF.preload('/computers_1-transformed.glb')
